notifications:
  email: false

language: node_js
node_js:
  - node

sudo: required

services:
  - docker
docker
before_install:
  -  docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten:sdk-incoming-64bit bash
  
script:make
  - docker exec -it emscripten  emcc helloworld.cpp -o helloworld.js --closure 1
  - make test
