notifications:
  email: false

language: node_js
node_js:
  - node

sudo: required

services:
  - docker
docker
before_install:
  -  docker run --rm -v $(pwd):/src trzeci/emscripten emcc helloworld.cpp -o helloworld.js --closure 1

script:
  - docker exec -it emscripten make helloworld.js
  - make test
